# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new build to closed beta"
  lane :beta do
    gradle(task: 'assemble', build_type: 'Release')
    upload_to_play_store(track: 'beta')
    slack(message: 'Successfully distributed a new beta build')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: ":app:bundleRelease")
    upload_to_play_store(track: 'alpha', skip_upload_apk: true)
  end
end
